# _config.yml
title: ketadata
markdown: kramdown
theme: null            # no theme; your HTML/CSS stays as-is
permalink: pretty      # /page/ instead of /page.html
exclude:
  - node_modules
  - README.md

# Process markdown in the /content folder
collections:
  content:
    output: true
    permalink: /:path/
